### ISSUE TITLE
State of the project and roadmap

### ISSUE THREAD

**Issue by quinn-dev** [andrew-sayers/sleep-diary-formats#1]
Hey,

first of all, I'm really excited to see other people working on Non-24 and circadian sleep disorder related projects, and I'm impressed by the work you have already done with this project.

Since I'm strongly considering contributing to the project, I'd like to know what the current state of the project is and what your roadmap for the future looks like.

One quite noticeable thing is the confusing structure of the project: Manually curated files are mixed up with computer-generated files (as in doc/), the repository serves the source code of the library, the source code of the documentation, the compiled library and the compiled documentation all in one place. For someone who's inexperienced with your code base, it's pretty difficult to get an overview.

Would you consider restructuring the project? I can make some suggestions, but in the end you are currently the project maintainer and would need to adopt to a new project structure.

The second thing I noticed is the library API itself. Don't get me wrong, it's certainly usable. But it's very unintuitive since it significantly differs from common JavaScript practices. Moreover it's written completely in CommonJS, which is completely fine, but I think the project could certainly benefit from a more modern toolchain.

Then again, it depends on what your plans are for this project.
In my opinion, restructuring both the project and the library's codebase could significantly improve the development workflow and would make it easier for others to contribute. I think this project could be a rock solid basis for many other projects to come, but for that it would need to be more accessible and mature.

I'll admit that's a lot of critique so far, but I want to stress that I really like everything you have done with this project so far and I appreciate your contribution to the Non-24 / CSRD community :heart:

**Comment by andrew-sayers** [comment]
Great questions!

The short answer is that the project is still coming together, so the future is still up for debate.  Since you mentioned restructuring around manual vs. auto-generated content, I'll start with the two big issues there.

The first issue is what to do with CSV.  I'm just now starting to realise how many CSV-based formats there are.  My old position was that it was better to write each format from scratch, because no two programs create CSV files quite the same - [CSV.md](/andrew-sayers/sleep-diary-formats/blob/main/src/CSV.md) goes into some detail about that.  But we could easily end up supporting ten or more CSV-like formats, so it would be good to find a way of streamlining that process.  That might just mean an abstract base class that does the boilerplate CSV work, or it might mean defining each format in some domain-specific language and auto-generating the actual code.  If we have to do the latter, the boundary between manual and automatic code will become much blurrier.

The second issue is containerisation.  This is the first time I've used Docker etc. to automate the development process, so I'm building up slowly and finding out what works.  Right now I've got a [Dockerfile](/andrew-sayers/sleep-diary-formats/blob/main/Dockerfile) and a [compilation script](/andrew-sayers/sleep-diary-formats/blob/main/bin/compile.sh) that *should* build everything in a safe and repeatable way, but I won't really know until I've done enough releases to see what goes wrong in the real world.  The next step after that is harder to see - for example, moving the build step server-side using GitHub Actions would reduce the burden on you, but would also create a bunch of new opportunities to introduce bugs into the public repository.

So restructuring the project is inevitable in the medium-term, but difficult in the short-term.  I guess my question is: what sort of changes are you interested in making?  If you're interested in format-agnostic functionality, I'd be interested to know what you make of [the standard format documentation](https://andrew-sayers.github.io/sleep-diary-formats/doc/DiaryStandard.html) - what you'd add, change, or move elsewhere.  If you'd rather add more formats, I'd be interested in your opinion about the [example format](/andrew-sayers/sleep-diary-formats/tree/main/src/Example).  The goal is to make it so you can copy that into a new directory and fill in the blanks, but so far I'm just collecting things in one place ready to use in a future solution.

I'm not quite sure what you're referring to with the changing the API and toolchain.  By which I mean, there are several unrelated things that are all worth examining :)

Starting with the toolchain, I've spent long enough thinking about build software that I'd want to hear a reason to switch, but not long enough that it would be impossible to do so.  For example, I went with Google's [Closure Compiler](https://developers.google.com/closure/compiler) instead of e.g. [webpack](https://webpack.js.org/) because it's the best at compiling modern JavaScript into something that runs in IE, and because all the things it's bad at don't apply to this particular project.  So I'm happy to talk about alternatives, but we'd need to talk about how it would improve (or at least not worsen) the user experience.

Moving on to the internal API between modules, I'm still trying to see what structure works best for the problems we actually need to solve.  For example, I'm currently trying to add spreadsheet support across the library.  That involves adding a module to handle generic spreadsheet stuff, finding a standard way to handle spreadsheets across most formats, then doing everything over from scratch in the one format that wants to be awkward.  So I'm keen to hear what a better API would look like, but be warned the answer might be "we can't have nice things because of this weird carbuncle we need to support".

And finishing with the most important thing, the public API.  It definitely needs more attention, but it's a bit of a chicken-and-egg problem - I can't tell what a good interface would look like without real world examples, and people can't use it in the real world without an API to work against.  [The documentation](https://andrew-sayers.github.io/sleep-diary-formats/doc/) starts with an example and includes some tutorials in the sidebar on the right, but it would be great to see the use cases I haven't thought of, and the interface that would best support them.

**Comment by quinn-dev** [comment]
In regards to manual vs auto-generated content: I'm mostly concerned about having computer-generated files as part of the repository (such as the compiled library, and the compiled JSDoc files). I think separating the source code from the compiled assets is a very good practice which yields various benefits.

In regards to CSV streamlining: If using a domain-specific language is already on the table, we could consider making the format parsing language-agnostic. This would also allow for the separation of the format documentation from the rest of the JavaScript library, and it would make the documented formats more accessible for developers using other programming languages. I'm not sure how much work this would be though.

In regards to containerization: What is the benefit of dockerizing the build process? Most JavaScript packages use a streamlined build process using a package manager (like npm or yarn) and various types of bundlers, which allows anyone with a basic development environment to build the packages. In that regards I really can't see the advantage of relying on a containerized build script to build a package which currently seems to have no dependencies whatsoever. Despite being quite a hassle, I also don't know what such a build process means for npm publishing. Are there specific reason for why you want to use this complicated build process?

I hope to answer the other points very soon.

**Comment by andrew-sayers** [comment]
Keeping generated files in the same repository makes things easier to manage - for example, it's easy to track which version of the documentation relates to which version of the code.  But GitHub nudges you to put documentation in a separate branch of the same repo, so the auto-generated stuff doesn't show up in the default list but is still versioned together - how does that sound?

A language-agnostic DSL is an interesting idea in the long-term, but it depends how things actually work out.  For example, it would be hard to extend such a DSL to cover [SleepChart 1.0](http://www.super-memory.com/articles/sleepchart.htm)'s inscrutable binary format.  My current guess is that there will be a handful of non-CSV formats that are better managed with code, and a mass of near-identical CSV formats that just need to be cranked out.  But I'm already standardising things a bit for spreadsheets, so it's just a matter of adding one thing at a time and seeing what opportunities present themselves.

The argument for containers is fairly simple - just as npm/yarn/etc. standardise JS packages, Docker etc. standardise things at the system level.  For example, there's a perennial issue where I happen to have some random package installed on my desktop, and it somehow winds up being used by a piece of code in a project.  So now there's an undocumented dependency I don't know about, and a randomly-selected half of people get weird errors when they try to compile it.  Containers avoid that problem by guaranteeing our environments are completely identical.

Having said that, it sounds like your issue with containers isn't so much with the implementation as the interface.  So my first question is: where would you expect to find the build instructions?  I don't want the main README to put off people who just want format docs, but I'm not sure where else to put them.  The guide is currently at [the bottom of doc/README.md](/andrew-sayers/sleep-diary-formats/tree/main/doc#compiling-the-project), but I'm open to suggestions.  Second question: what would better instructions look like?  Do you have any examples of projects with great build docs that we could borrow from?

**Comment by andrew-sayers** [comment]
Having read back through this conversation, I think we might be talking past each other about building the project.  The build system basically consists of three files:

1. [Dockerfile](/andrew-sayers/sleep-diary-formats/blob/main/Dockerfile) describes the OS for building packages.  My previous comment discussed the value of that file, so I won't labour the point here
2. [Makefile](/andrew-sayers/sleep-diary-formats/blob/main/Makefile) defines the main build process.  I generally use Makefiles as a placeholder until a project is mature enough to pick a good solution.  We're probably getting to that point now, so we can talk about replacing it with something more node-like
3. [compile.sh](/andrew-sayers/sleep-diary-formats/blob/main/bin/compile.sh) defines all the little extras that build systems don't cover (for example, the code to manage a `doc` branch would go in there).  We can try moving things into a cleverer build system, but I'd be surprised if we got rid of it altogether

The `Dockerfile` does currently `npm install -g` a few packages.  I seem to remember those packages failing to run when installed locally, and and generally eating up more time than they were worth.  I would have been stretched fairly thin at the time, and just put up with something that worked and let me move on to the next problem.  If you can get it to work properly, we can definitely move that line into a build system.

**Comment by quinn-dev** [comment]
First of all, I'm not opposed to using a containerized build system **in addition** to a JavaScript-based build system. But I think having a JavaScript-based build system is pretty important, and I currently see no reason for relying on Docker to build a JavaScript library. After all, Docker is an absolutely massive, massively restrictive dependency.

A docker-based build system is very platform-restrictive, at least compared to a JavaScript build system. It does not run on all systems that support JavaScript, and there are plenty of cases where installing Docker as part of your development environment is not feasible, at least not for compiling a single JavaScript module.

It also makes it a huge hassle to incorporate this library into any potential project that's based on it. By requiring Docker for the build step, we are passing on this dependency to every project that's based on this library, and there are many use cases where having Docker as a dependency is simply not worth it.

I think Docker has many valid use cases, but I don't think that the library build process should depend on it unless technically required.

**Comment by andrew-sayers** [comment]
So it sounds like we're talking about two different use cases.  The release process involves creating repeatable builds, detecting missing dependencies, and so on - that means a container where the build environment can be properly controlled.  But so long as those checks are done somewhere, it's fine for everyone else to build things however they like.  Even the current system doesn't technically *require* Docker - I just haven't put much time into optimising or documenting a pathway I'm supposed to avoid.

Incidentally, GitHub Actions might well be another use case for Docker.  So far as I can tell, they take a `Dockerfile` and some configuration; then they run any script you like in response to certain events.  I think that means GitHub itself could some day test PRs and build binaries automatically, even for people who just want to scribble out one-line fixes in Notepad.  There's a lot of work to be done before we get there, and there could be some technical reason why it's impossible, but it seems like a worthwhile goal to aim for.

Speaking of PRs, it might be more productive to talk about the build system by reviewing some actual code.  Would you mind writing up something that shows what you think it should look like?  It can be a broad concept with pseudocode and `TODO` blocks for the time-consuming bits if you like - it just needs to provoke a more concrete discussion.

**Comment by quinn-dev** [comment]
Yes, I think we are talking about two different use cases.
I'd just like to clarify one thing: Why do you want to build the library before you ship it?
Most open-source JS libraries nowadays are imported from source (usually through npm) and then build together with all the other libraries used in the project. The build system you seem to be proposing does not follow this approach and I wonder why.

Indeed, npm availability greatly increases adoption (since every JS developer is familiar with it) and also provides more flexibility for the developer since they can use all sorts of JS toolchaining in their project which is based on npm.

I agree regarding the PRs. I will try to create a PR soon which shows a basic implementation of a JS-based build system.

**Comment by andrew-sayers** [comment]
To some extent, building the library locally is the solution I could achieve in the time available.  The documentation needs to be built locally so it can go up on GitHub Pages, and I need to build everything regularly so I can test it, so `git add sleep-diary-formats.js` was the quick fix.  If we can get it up on npm and into a CDN, so much the better.

The primary use case to think about is: imagine you're talking to a novice developer who has written a web-based "Hello, World!" but hasn't heard of package management.  How do you get them using the library with the absolute minimum amount of work?  What mistakes are they likely to make, and how do you guide them away from those mistakes?

[The browser quick-start guide](https://github.com/andrew-sayers/sleep-diary-formats/tree/main/doc#browser-quick-start) is my latest go at that problem - copy/paste two lines of HTML and some boilerplate JS, download the library (which I should have linked to more prominently), and off you go.

There's also a Node.JS quick-start section, but like with most node issues it needs more attention than I've given it so far.  I look forward to something more useful :)

The simplicity of the browser interface is actually a bit of a cheat.  [The DiaryLoader class](https://github.com/andrew-sayers/sleep-diary-formats/blob/f50a16a8da9dc7e91987b5b57e6f1e1d06eca568/src/DiaryBase.js#L374) quietly pulls in dependencies and does some setup work that's only relevant in a browser.  Thinking about it, I'll move that class into a separate file so node folk can ignore it altogether.  I would ask you to move it, but I've got a bunch of unrelated changes queued up so we'd just be creating merge conflicts for ourselves.

An npm release also needs to think about versioning.  I'm currently adding spreadsheet support throughout the library, which will cause some minor changes to the public API.  And after that, the generic solution for simple formats might break the public API again and will cause significant changes for internal APIs.  But after that, we might just add more formats forever without changing the API at all.  If the code is distributed on a CDN, we'll need some kind of link like `https://$cdn/.../1.x/sleep-diary-formats.min.js` for people who want to get new formats automatically without worrying about breakage.

And for the record, compiling the library is implicitly part of the pre-release testing process, likely to grow with time.  The compiler points out a lot of issues that are legal JS but clearly bugs, and I'll probably want to add new code analysis tools some day.  Of course that doesn't mean we have to ship the locally-compiled version, just that it needs to be a comfortable part of the development process.

**Comment by andrew-sayers** [comment]
Not sure if you're still interested, but I'm now preparing to release the spreadsheet code I've been working on for the past few months, including some of the improvements we discussed here.

I'm currently finishing off the documentation, which means moving compiled code to a separate branch.  And this release will handle CSVs as a special case of spreadsheets - seems like the best compromise, and even kinda obvious when I say it out loud.

Would you like to review the new release?  If so, I'll need to spend some time splitting the minor improvements (typos, bug fixes etc.) from the big changes (refactoring most of the codebase).  Let me know in the next few days, and I'll figure something out.

**Comment by andrew-sayers** [comment]
The new release is finally out, so I'm going to close this one.  Feel free to reopen if you come back to it.

A few last points:

Auto-generated code has all been moved to the `gh-pages` branch.  This branch is managed by a new GitHub Action, so there shouldn't be any danger of it going out of sync with `main`.

Docker doesn't (yet) seem to be necessary for GitHub Actions, so we'll see how that evolves in future.

And I've created an organisation, so the official version of the project is now [sleep-diary-formats/sleep-diary-formats.github.io](https://github.com/sleep-diary-formats/sleep-diary-formats.github.io), and the site has [a nicer URL](https://sleep-diary-formats.github.io/).
